### ISSUE TITLE
Use booloader (barebox) to load images ?!

### ISSUE THREAD

**Issue by ricardojlrufino** [rsta2/circle#116]
Hi, is possible use a bootloader like barebox (https://barebox.org/) to load kernel / circle images.. ?

**Comment by rsta2** [comment]
Circle comes with its own [serial bootloader](https://github.com/rsta2/circle/blob/master/doc/bootloader.txt) and [sample/38-bootloader](https://github.com/rsta2/circle/tree/master/sample/38-bootloader) is a network bootloader with Web frontend and TFTP support. I haven't tried Barebox, so I cannot talk about it.

**Comment by ricardojlrufino** [comment]
thanks
