### ISSUE TITLE
GLES2 sample?

### ISSUE THREAD

**Issue by juj** [rsta2/circle#128]
Hi,

the README mentioned that using GLES2 would be possible? Any chance there might be an example/sample program around to help figure out how to get going with GLES2 rendering? I suppose GLES2 rendering will utilize the GPU on the Pi? (as opposed to doing software rasterization?)

**Comment by rsta2** [comment]
An OpenGL ES 2.0 sample is [here](https://github.com/rsta2/circle/tree/master/addon/vc4/interface/sample/hello_triangle2). Yes, rendering uses the GPU in this case.

**Comment by juj** [comment]
Perfect, thanks for pointing my way! Awesome project btw :)
