### ISSUE TITLE
Quest about the memory mapping for the framebuffer?

### ISSUE THREAD

**Issue by sjtugjy** [rsta2/circle#161]
I am encountering a problem with the framebuffer (I write a simple demo on my toy OS instead of using circle):

I map the framebuffer as NORMAL memory (cacheable) and then need to flush the cache to output all the content.
If I map the framebuffer as DEVICE memory, drawing a new line will be very slow although no cache flush is needed now.

I work on RASPI3B+ and set disable_l2cache=0 in the config.txt.
Any suggestion? Thanks.

**Comment by rsta2** [comment]
Circle is mapping the framebuffer as device memory. That's all I can tell here.

**Comment by sjtugjy** [comment]
Device-nGnRnE?

**Comment by rsta2** [comment]
No, device-nGnRE.

**Comment by rsta2** [comment]
I think, this is a bit off-topic and can be closed.
