### ISSUE TITLE
Sample program for FATFS and USB storage devices doesn't seem to work

### ISSUE THREAD

**Issue by toptensoftware** [rsta2/circle#189]
I've been trying to learn how to use USB storage devices, and was looking at sample 39.  It works fine using CFATFileSystem, but if I set USE_FATFS nothing seems to happen - inserting and removing drives does nothing... perhaps even hangs, not sure.  The drive has a single partition (not sure if that matters).

I can dig in further but wanted to check with you to see if there's anything else that might be breaking this.

Running from develop branch (but nothing changed) on Pi2.

**Comment by rsta2** [comment]
The sample/39-umsdplugging from the *develop* branch does work here with `USE_FATFS`. I have tested this again on a RPi 2B with two different USB flash drives. Did you make `make clean` after setting `USE_FATFS`? Are you using the firmware downloaded in boot/?

**Comment by toptensoftware** [comment]
Thanks Rene... leaving it with me and I'll take a fresh look at it again tonight.

**Comment by toptensoftware** [comment]
Had another look at this and it appears to be related to the USB to SD Card adapter I'm using.  When I switched to a different (older) one it seems to work much better even with the same SD card.

Not sure if it helps, but below is some details on what seems to be going wrong.

Finally (and I'm not entirely sure about this) but it seems to work better when I put the sample 39 kernel image direcrtly on the Pi's boot SD card rather than flashing with the bootloader.  Are there cases the boot loader can't handle?  (Also, just to be clear I'm using the latest development branch with none of my recent changes for everything - a fresh git clone to a different directory). I'm using the recommended 9.2 ARM toolchain.

To answer questions: Yes, I did clean after changing `USE_FATFS` and Yes, using firmware from boot directory.  Running 32-bit arch.
---

With the poorly behaving adapter, with CFATFileSystem I get this error:

![image](https://user-images.githubusercontent.com/179862/104871177-7d7d4a80-599e-11eb-920e-ac83878b1976.png)

Similar with FATFS:

![image](https://user-images.githubusercontent.com/179862/104871186-8706b280-599e-11eb-8859-ef8bc9674bf3.png)

The adapter that's causing trouble is this:

![IMG_9422](https://user-images.githubusercontent.com/179862/104871480-40fe1e80-599f-11eb-8c08-d99c1e40bbdc.jpg)

**Comment by rsta2** [comment]
I wonder, because there is no `assert (!(usChangeStatus & C_PORT_ENABLE__MASK))` in line 566 of *usbstandardhub.cpp* on the *develop* branch. It has been removed there recently. Are you testing the version from *master* be any chance?

**Comment by toptensoftware** [comment]
Hi Rene,  sorry to have wasted your time.  I must have mistyped my checkout command after the fresh clone of the repo and forgot to include the remote name... so my develop branch was just a branch from master.  Silly mistake. Working fine now, thank you.
