### ISSUE TITLE
Notable clang warning regarding comparison that is always true

### ISSUE THREAD

**Issue by smuehlst** [rsta2/circle#20]
I have submitted pull request #19 to fix some minor code issues reported by clang. An additional notable warning reported by clang which probably should be investigated is the following:

    bcmframebuffer.cpp:93:36: warning: comparison of constant 256 with expression of type 'u8' (aka 'unsigned char') is always true [-Wtautological-constant-out-of-range-compare]
        if (m_pInfo->Depth <= 8 && nIndex < 256)
                                   ~~~~~~ ^ ~~~

As nIndex is declared as `u8` in the parameter list of `CBcmFrameBuffer::SetPalette`, the comparison `nIndex < 256` is always true.

**Comment by rsta2** [comment]
Thanks for reporting this issue! This if-condition is obsolete. I removed it.
