### ISSUE TITLE
USB peripheral mode

### ISSUE THREAD

**Issue by sebastienNEC** [rsta2/circle#202]
Hello, I am wondering how much effort would be needed to implement USB peripheral role, particularly for devices with an USB On-The-Go capability?
Thank you !

**Comment by rsta2** [comment]
That would be a big effort, because one have to analyze the Linux driver to extract the required information. I did this for the host mode and it wasn't fun. ;) There is no public documentation available for the USB DWC OTG controller of the Raspberry Pi.

**Comment by sebastienNEC** [comment]
Ah ok, thank you for the info and thank you for the hard work !

**Comment by rsta2** [comment]
See: #387

**Comment by rsta2** [comment]
Support for the USB MIDI (v1.0) gadget (aka peripheral) mode is in Circle 45.3.
