### ISSUE TITLE
FTDI USB device 0403:6010 not recognized by Circle 

### ISSUE THREAD

**Issue by hpingel** [rsta2/circle#220]
One of the Sidekick64 network testers has an unrecognized FTDI USB device and I patched it into the circle source. He reports it to be working fine. It would be cool if you could add this to circle, Rene! Thank you in advance!

Linux reports the device as:
Bus 002 Device 005: ID 0403:6010 Future Technology Devices International, Ltd FT2232C/D/H Dual UART/FIFO IC

I created a pull request with the necessary change: https://github.com/rsta2/circle/pull/219

**Comment by rsta2** [comment]
I merged it. Thank you!
