### ISSUE TITLE
Suggestion - Add CMake capability

### ISSUE THREAD

**Issue by Memotech-Bill** [rsta2/circle#226]
It would be nice if Circle had the CMakeLists.txt files needed to turn Circle into a CMake INTERFACE library similar to the SDK for the RPi Pico.

This would make it easier to have projects that will build for either Pico or bare-metal RPi.

**Comment by rsta2** [comment]
I have to do some reading, when I have some time left, because I did not use CMake so far. Currently I think, the Circle build system is good. It does work with toolchain, make, shell only, is easy to setup and configure and checks file dependencies. So CMake could only be another option and I have to check, if the additional effort is worth doing.

**Comment by Memotech-Bill** [comment]
One further advantage of CMake is that it does out of source tree builds. This means that it would be easy to have different build folders for each Raspberry Pi type (1-4), rather than having to do a "make clean" and a full rebuild when changing type.

**Comment by Memotech-Bill** [comment]
For information, I have now got CMake to compile enough of Circle for my purposes. My approach is slightly different in that the CMake definitions are outside the Circle source tree, but may still be useful. In my main CMakeLists.txt file I have:

`
  set(CMAKE_CXX_STANDARD 14)

  project(memu C CXX ASM)

  set(CIRCLE_DIR ${CMAKE_CURRENT_LIST_DIR}/../circle)

  set(CMAKE_LINKER ld)
  set(CMAKE_CXX_LINK_EXECUTABLE
    "<CMAKE_LINKER> -o <TARGET> <LINK_FLAGS> <OBJECTS> --start-group <LINK_LIBRARIES> --end-group")

  if (${RPI} EQUAL 1)
    set(ARCH -DAARCH=32 -mcpu=arm1176jzf-s -marm -mfpu=vfp -mfloat-abi=hard)
    add_compile_definitions(RASPPI=1)
    set(KERNEL kernel.img)
  elseif (${RPI} EQUAL 2)
    set(ARCH -DAARCH=32 -mcpu=cortex-a7 -marm -mfpu=neon-vfpv4 -mfloat-abi=hard)
    add_compile_definitions(RASPPI=2)
    set(KERNEL kernel7.img)
  elseif (${RPI} EQUAL 3)
    set(ARCH -DAARCH=32 -mcpu=cortex-a53 -marm -mfpu=neon-fp-armv8 -mfloat-abi=hard)
    add_compile_definitions(RASPPI=3)
    set(KERNEL kernel8-32.img)
  elseif (${RPI} EQUAL 4)
    set(ARCH -DAARCH=32 -mcpu=cortex-a72 -marm -mfpu=neon-fp-armv8 -mfloat-abi=hard)
    add_compile_definitions(RASPPI=4)
    set(KERNEL kernel7l.img)
  endif()

  add_compile_definitions(__circle__)
  add_compile_options(${ARCH})
  add_compile_options($<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>)
  add_compile_options($<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>)
  add_compile_options($<$<COMPILE_LANGUAGE:CXX>:-nostdinc++>)
  add_compile_options(-O2)
  add_compile_options(-Wall -fsigned-char -ffreestanding)
  add_compile_options($<$<COMPILE_LANGUAGE:CXX>:-std=c++14>)
  add_compile_options($<$<COMPILE_LANGUAGE:CXX>:-Wno-aligned-new>)
  add_link_options(--section-start=.init=0x8000)
  add_link_options(-T ${CIRCLE_DIR}/circle.ld)
  add_compile_definitions(
    STDLIB_SUPPORT=1
    __VCCOREVER__=0x04000000
    )
  add_compile_options(
    -U__unix__
    -U__linux__
    )

  execute_process(COMMAND ${CMAKE_C_COMPILER} ${ARCH} -print-file-name=libgcc.a
                OUTPUT_VARIABLE LIBGCC_PATH
                OUTPUT_STRIP_TRAILING_WHITESPACE)

  execute_process(COMMAND ${CMAKE_C_COMPILER} ${ARCH} -print-file-name=libm.a
                OUTPUT_VARIABLE LIBM_PATH
                OUTPUT_STRIP_TRAILING_WHITESPACE)
              
  add_executable(memu-circle)

  target_compile_definitions(memu-circle PUBLIC
    -DAARCH=32
    -D__circle__
    )

  include_directories(
    ${CIRCLE_DIR}/include
    ${CIRCLE_DIR}/addon
    ${CMAKE_CURRENT_LIST_DIR}/circle/include
    )

  add_subdirectory(circle)

  target_link_libraries(memu-circle PUBLIC
    memu_src
    Z80_emu
    fatfs
    circle_fs
    circle_sdcard
    circle_sound
    circle_vchiq
    circle_usb
    circle_input
    circle_sched
    circle_linux
    circle_lib
    ${LIBM_PATH}
    ${LIBGCC_PATH}
    )

  add_custom_command(TARGET memu-circle POST_BUILD
    COMMAND objcopy memu-circle -O binary ${KERNEL}
    )
`
And then in my circle subfolder, I have another CMakeLists.txt file:

`
add_library(circle_lib STATIC)
  
target_sources(circle_lib PRIVATE
  ${CIRCLE_DIR}/lib/actled.cpp
  ${CIRCLE_DIR}/lib/alloc.cpp
  ${CIRCLE_DIR}/lib/assert.cpp
  ${CIRCLE_DIR}/lib/bcmframebuffer.cpp
  ${CIRCLE_DIR}/lib/bcmmailbox.cpp
  ${CIRCLE_DIR}/lib/bcmpropertytags.cpp
  ${CIRCLE_DIR}/lib/cache-v7.S
  ${CIRCLE_DIR}/lib/chainboot.cpp
  ${CIRCLE_DIR}/lib/chargenerator.cpp
  ${CIRCLE_DIR}/lib/classallocator.cpp
  ${CIRCLE_DIR}/lib/cputhrottle.cpp
  ${CIRCLE_DIR}/lib/debug.cpp
  ${CIRCLE_DIR}/lib/delayloop.S
  ${CIRCLE_DIR}/lib/device.cpp
  ${CIRCLE_DIR}/lib/devicenameservice.cpp
  ${CIRCLE_DIR}/lib/dmachannel.cpp
  ${CIRCLE_DIR}/lib/exceptionhandler.cpp
  ${CIRCLE_DIR}/lib/exceptionstub.S
  ${CIRCLE_DIR}/lib/gpioclock.cpp
  ${CIRCLE_DIR}/lib/gpiomanager.cpp
  ${CIRCLE_DIR}/lib/gpiopin.cpp
  ${CIRCLE_DIR}/lib/gpiopinfiq.cpp
  ${CIRCLE_DIR}/lib/heapallocator.cpp
  ${CIRCLE_DIR}/lib/i2cmaster.cpp
  ${CIRCLE_DIR}/lib/i2cslave.cpp
  ${CIRCLE_DIR}/lib/i2ssoundbasedevice.cpp
  ${CIRCLE_DIR}/lib/koptions.cpp
  ${CIRCLE_DIR}/lib/latencytester.cpp
  ${CIRCLE_DIR}/lib/logger.cpp
  ${CIRCLE_DIR}/lib/macaddress.cpp
  ${CIRCLE_DIR}/lib/machineinfo.cpp
  ${CIRCLE_DIR}/lib/memory.cpp
  ${CIRCLE_DIR}/lib/multicore.cpp
  ${CIRCLE_DIR}/lib/netdevice.cpp
  ${CIRCLE_DIR}/lib/new.cpp
  ${CIRCLE_DIR}/lib/nulldevice.cpp
  ${CIRCLE_DIR}/lib/numberpool.cpp
  ${CIRCLE_DIR}/lib/pageallocator.cpp
  ${CIRCLE_DIR}/lib/pagetable.cpp
  ${CIRCLE_DIR}/lib/ptrarray.cpp
  ${CIRCLE_DIR}/lib/ptrlist.cpp
  ${CIRCLE_DIR}/lib/purecall.cpp
  ${CIRCLE_DIR}/lib/pwmoutput.cpp
  ${CIRCLE_DIR}/lib/pwmsoundbasedevice.cpp
  ${CIRCLE_DIR}/lib/pwmsounddevice.cpp
  ${CIRCLE_DIR}/lib/qemu.cpp
  ${CIRCLE_DIR}/lib/screen.cpp
  ${CIRCLE_DIR}/lib/serial.cpp
  ${CIRCLE_DIR}/lib/setjmp.S
  ${CIRCLE_DIR}/lib/soundbasedevice.cpp
  ${CIRCLE_DIR}/lib/spimasteraux.cpp
  ${CIRCLE_DIR}/lib/spimaster.cpp
  ${CIRCLE_DIR}/lib/spimasterdma.cpp
  ${CIRCLE_DIR}/lib/spinlock.cpp
  ${CIRCLE_DIR}/lib/startup.S
  ${CIRCLE_DIR}/lib/string.cpp
  ${CIRCLE_DIR}/lib/synchronize.cpp
  ${CIRCLE_DIR}/lib/sysinit.cpp
  ${CIRCLE_DIR}/lib/time.cpp
  ${CIRCLE_DIR}/lib/timer.cpp
  ${CIRCLE_DIR}/lib/tracer.cpp
  ${CIRCLE_DIR}/lib/usertimer.cpp
  ${CIRCLE_DIR}/lib/util.cpp
  ${CIRCLE_DIR}/lib/util_fast.S
  ${CIRCLE_DIR}/lib/virtualgpiopin.cpp
  ${CIRCLE_DIR}/lib/writebuffer.cpp
  )

if (${RPI} EQUAL 4)
  target_sources(circle_lib PRIVATE
      ${CIRCLE_DIR}/lib/bcm54213.cpp
      ${CIRCLE_DIR}/lib/bcmpciehostbridge.cpp
      ${CIRCLE_DIR}/lib/bcmrandom200.cpp
      ${CIRCLE_DIR}/lib/interruptgic.cpp
      ${CIRCLE_DIR}/lib/dma4channel.cpp
      ${CIRCLE_DIR}/lib/devicetreeblob.cpp
      )
else()
  target_sources(circle_lib PRIVATE
    ${CIRCLE_DIR}/lib/bcmrandom.cpp
    ${CIRCLE_DIR}/lib/interrupt.cpp
    )
endif()


add_library(circle_linux STATIC)

target_sources(circle_linux PRIVATE
  ${CIRCLE_DIR}/addon/linux/timer.cpp
  ${CIRCLE_DIR}/addon/linux/interrupt.cpp
  ${CIRCLE_DIR}/addon/linux/linuxemu.cpp
  ${CIRCLE_DIR}/addon/linux/pthread.cpp
  ${CIRCLE_DIR}/addon/linux/linuxdevice.cpp
  ${CIRCLE_DIR}/addon/linux/platform_device.cpp
  ${CIRCLE_DIR}/addon/linux/device.cpp
  ${CIRCLE_DIR}/addon/linux/mutex.cpp
  ${CIRCLE_DIR}/addon/linux/raspberrypi-firmware.cpp
  ${CIRCLE_DIR}/addon/linux/semaphore.cpp
  ${CIRCLE_DIR}/addon/linux/kthread.cpp
  ${CIRCLE_DIR}/addon/linux/spinlock.cpp
  ${CIRCLE_DIR}/addon/linux/bug.cpp
  ${CIRCLE_DIR}/addon/linux/completion.cpp
  ${CIRCLE_DIR}/addon/linux/sprintf.cpp
  ${CIRCLE_DIR}/addon/linux/rwlock.cpp
  ${CIRCLE_DIR}/addon/linux/dma-mapping.cpp
  ${CIRCLE_DIR}/addon/linux/printk.cpp
  ${CIRCLE_DIR}/addon/linux/delay.cpp
  )

add_library(circle_sdcard STATIC)

target_sources(circle_sdcard PRIVATE
  ${CIRCLE_DIR}/addon/SDCard/emmc.cpp
  ${CIRCLE_DIR}/addon/SDCard/mmchost.cpp
  ${CIRCLE_DIR}/addon/SDCard/sample/kernel.cpp
  ${CIRCLE_DIR}/addon/SDCard/sample/main.cpp
  ${CIRCLE_DIR}/addon/SDCard/sdhost.cpp
  )

add_library(circle_vchiq STATIC)

target_sources(circle_vchiq PRIVATE
  ${CIRCLE_DIR}/addon/vc4/vchiq/vchiq_kern_lib.c
  ${CIRCLE_DIR}/addon/vc4/vchiq/vchiq_shim.c
  ${CIRCLE_DIR}/addon/vc4/vchiq/vchiq_connected.c
  ${CIRCLE_DIR}/addon/vc4/vchiq/vchiq_2835_arm.c
  ${CIRCLE_DIR}/addon/vc4/vchiq/vchiq_core.c
  ${CIRCLE_DIR}/addon/vc4/vchiq/vchiq_arm.c
  ${CIRCLE_DIR}/addon/vc4/vchiq/vchiqdevice.cpp
  ${CIRCLE_DIR}/addon/vc4/vchiq/vchiq_util.c
  )

add_library(circle_sound STATIC)

target_sources(circle_sound PRIVATE
  ${CIRCLE_DIR}/addon/vc4/sound/vchiqsoundbasedevice.cpp
  ${CIRCLE_DIR}/addon/vc4/sound/vchiqsounddevice.cpp
  )

add_library(circle_usb STATIC)

target_sources(circle_usb PRIVATE
  ${CIRCLE_DIR}/lib/usb/usbgamepadps4.cpp
  ${CIRCLE_DIR}/lib/usb/usbkeyboard.cpp
  ${CIRCLE_DIR}/lib/usb/usbrequest.cpp
  ${CIRCLE_DIR}/lib/usb/usbdevicefactory.cpp
  ${CIRCLE_DIR}/lib/usb/usbstring.cpp
  ${CIRCLE_DIR}/lib/usb/usbserialcdc.cpp
  ${CIRCLE_DIR}/lib/usb/usbgamepad.cpp
  ${CIRCLE_DIR}/lib/usb/usbmassdevice.cpp
  ${CIRCLE_DIR}/lib/usb/usbgamepadstandard.cpp
  ${CIRCLE_DIR}/lib/usb/usbdevice.cpp
  ${CIRCLE_DIR}/lib/usb/lan7800.cpp
  ${CIRCLE_DIR}/lib/usb/usbserialpl2303.cpp
  ${CIRCLE_DIR}/lib/usb/usbserialch341.cpp
  ${CIRCLE_DIR}/lib/usb/usbmidi.cpp
  ${CIRCLE_DIR}/lib/usb/usbprinter.cpp
  ${CIRCLE_DIR}/lib/usb/usbserial.cpp
  ${CIRCLE_DIR}/lib/usb/usbfunction.cpp
  ${CIRCLE_DIR}/lib/usb/usbstandardhub.cpp
  ${CIRCLE_DIR}/lib/usb/usbconfigparser.cpp
  ${CIRCLE_DIR}/lib/usb/usbgamepadxbox360.cpp
  ${CIRCLE_DIR}/lib/usb/usbmouse.cpp
  ${CIRCLE_DIR}/lib/usb/usbhostcontroller.cpp
  ${CIRCLE_DIR}/lib/usb/usbhiddevice.cpp
  ${CIRCLE_DIR}/lib/usb/usbgamepadps3.cpp
  ${CIRCLE_DIR}/lib/usb/usbgamepadswitchpro.cpp
  ${CIRCLE_DIR}/lib/usb/usbbluetooth.cpp
  ${CIRCLE_DIR}/lib/usb/usbgamepadxboxone.cpp
  ${CIRCLE_DIR}/lib/usb/usbserialft231x.cpp
  ${CIRCLE_DIR}/lib/usb/usbendpoint.cpp
  ${CIRCLE_DIR}/lib/usb/smsc951x.cpp
  ${CIRCLE_DIR}/lib/usb/usbcdcethernet.cpp
  ${CIRCLE_DIR}/lib/usb/usbserialcp2102.cpp
  )

if (${RPI} EQUAL 4)
  target_sources(circle_usb PRIVATE
    ${CIRCLE_DIR}/lib/usb/xhciring.cpp
    ${CIRCLE_DIR}/lib/usb/xhciroothub.cpp
    ${CIRCLE_DIR}/lib/usb/xhcidevice.cpp
    ${CIRCLE_DIR}/lib/usb/xhciusbdevice.cpp
    ${CIRCLE_DIR}/lib/usb/xhcislotmanager.cpp
    ${CIRCLE_DIR}/lib/usb/xhcimmiospace.cpp
    ${CIRCLE_DIR}/lib/usb/xhcicommandmanager.cpp
    ${CIRCLE_DIR}/lib/usb/xhciendpoint.cpp
    ${CIRCLE_DIR}/lib/usb/xhcirootport.cpp
    ${CIRCLE_DIR}/lib/usb/xhcisharedmemallocator.cpp
    ${CIRCLE_DIR}/lib/usb/xhcieventmanager.cpp
    )
else()
  target_sources(circle_usb PRIVATE
    ${CIRCLE_DIR}/lib/usb/dwhcixactqueue.cpp
    ${CIRCLE_DIR}/lib/usb/dwhcirootport.cpp
    ${CIRCLE_DIR}/lib/usb/dwhcidevice.cpp
    ${CIRCLE_DIR}/lib/usb/dwhciframeschednper.cpp
    ${CIRCLE_DIR}/lib/usb/dwhciregister.cpp
    ${CIRCLE_DIR}/lib/usb/dwhciframeschedper.cpp
    ${CIRCLE_DIR}/lib/usb/dwhcixferstagedata.cpp
    ${CIRCLE_DIR}/lib/usb/dwhciframeschednsplit.cpp
    )
endif()

add_library(circle_sched STATIC)

target_sources(circle_sched PRIVATE
  ${CIRCLE_DIR}/lib/sched/task.cpp
  ${CIRCLE_DIR}/lib/sched/scheduler.cpp
  ${CIRCLE_DIR}/lib/sched/taskswitch.S
  ${CIRCLE_DIR}/lib/sched/synchronizationevent.cpp
  )

add_library(circle_input STATIC)

target_sources(circle_input PRIVATE
  ${CIRCLE_DIR}/lib/input/console.cpp
  ${CIRCLE_DIR}/lib/input/keyboardbehaviour.cpp
  ${CIRCLE_DIR}/lib/input/keyboardbuffer.cpp
  ${CIRCLE_DIR}/lib/input/keymap.cpp
  ${CIRCLE_DIR}/lib/input/linediscipline.cpp
  ${CIRCLE_DIR}/lib/input/mousebehaviour.cpp
  ${CIRCLE_DIR}/lib/input/mouse.cpp
  ${CIRCLE_DIR}/lib/input/touchscreen.cpp
  )

add_library(circle_fs)

target_sources(circle_fs PRIVATE
  ${CIRCLE_DIR}/lib/fs/partition.cpp
  ${CIRCLE_DIR}/lib/fs/partitionmanager.cpp
  )
`

For an in-source-tree implementation, this latter file would be split into multiple CMaleLists.txt files, one per folder, and the source files specified as ${CMAKE_CURRENT_LIST_DIR}/filename.

**Comment by rsta2** [comment]
Thanks for showing, how it may work. But as I told, CMake can only be another option for a Circle build system. There are many projects out there, which use the current build system and all them would have to be modified, if I would come with a new system now. This will not happen. I also do not see that much advantages, over the current build system. That one can have multiple object versions is a nice, but honestly Circle builds quick enough to rebuild it, if required, because it's small. I think, there are more people, which are familiar with make than with CMake (including me). I do not see, CMake in Circle in the near future. Changing the build system is a big step.

**Comment by kevinboone** [comment]
I'd like to point out that the use of CMake is a _disincentive_ to many people working on the Pi Pico. I'm aware that some people like it and, of course, that's fine. It would be a sad world if we were all the same. However, the problem with the Pico is that it's almost impossible to work without using CMake. CMake is fine for some things, but it's highly opinionated. Personally, I think the way that Circle builds is fine as it is. Just my $0.02, of course.

**Comment by rsta2** [comment]
Thanks @kevinboone. Good to hear your opinion. Recently I worked with the RPI Pico and I think, using CMake with it is OK. But this does not mean, that it is necessary to use CMake for Circle too, when you want to share files between the projects. So I think that the Circle build system can remain and this issue can be closed soon.

**Comment by Memotech-Bill** [comment]
I never intended to suggest that CMake should be the only build option for Circle, only that it would be nice to have a CMake file available as an alternate build option. I do recognise the extra work involved in maintaining multiple build options.

I wrote my own CMake file to build what I needed from Circle.

As far as I am concerned this issue may be closed.

**Comment by rsta2** [comment]
@Memotech-Bill Thanks for clarifying your position. Yes, there are many Makefiles in Circle and maintaining another build system would require more time, which can probably be used better for other things. And if you have solved this problem for yourself, I will close this issue.
