### ISSUE TITLE
CCharGenerator::GetCharWidth returning zero

### ISSUE THREAD

**Issue by giuseppe-avon** [rsta2/circle#238]
During CScreen::Initialize() function, what are the conditions that could lead GetCharWidth() function returning a zero instead of the real character width size? Thanks.

**Comment by giuseppe-avon** [comment]
To be more specific
CScreenDevice::ClearLineEnd (this=0x22f308 <piBridge+3592>) at screen.cpp:558
558             for (unsigned nPosX = m_nCursorX; nPosX < m_nWidth; nPosX += m_CharGen.GetCharWidth ())

m_CharGen.GetCharWidth() is always 0 and this for loop is never ending. This happens when I link my own library, which in turn calls the CStdLibApp from the Circle-StdLib.

**Comment by rsta2** [comment]
`CCharGenerator::GetCharWidth()` can only return zero, when the constructor `CCharGenerator::CCharGenerator()` was not called properly (yet) or the `this` pointer is wrong.

**Comment by rsta2** [comment]
I think, this can be closed.
