### ISSUE TITLE
HDMI display not working properly.

### ISSUE THREAD

**Issue by stay26** [rsta2/circle#244]
Board used : Raspberry pi 2 model B v1.1
I am trying to run sample code on my raspberry pi. But there is blank bar all around the display. I had tried many display but same result.
Thanks in advance.
![IMG_20210811_154735](https://user-images.githubusercontent.com/88774146/129012923-9d8bbe61-e175-4d29-9235-b9e8f9479ed9.jpg)

**Comment by dwhinham** [comment]
Try `disable_overscan=1` in `config.txt`.

**Comment by stay26** [comment]
Thanks for reply but i don't know where is config.txt file.

**Comment by stay26** [comment]
Thanks, issue is solved.

**Comment by stay26** [comment]
On my monitor bezels at top and bottom still there. Only side bezels are gone.

**Comment by rsta2** [comment]
Circle has no influence on the overscan display settings, this is done independently by the firmware. You can only try to eliminate the borders with the *config.txt* settings in [this section](https://www.raspberrypi.org/documentation/computers/config_txt.html#generic-display-options), but not sure, if this will work for all display resolutions.

**Comment by stay26** [comment]
Thank you for fast reply. Now i understand the whole concept of display drivers.

**Comment by stay26** [comment]
Thank you for fast reply. Issue is solved.
