### ISSUE TITLE
Splash screen change

### ISSUE THREAD

**Issue by stay26** [rsta2/circle#247]
Is there any way to change splash screen logo with other image.

**Comment by rsta2** [comment]
Circle itself does not have a splash screen. If you mean the rainbow screen, displayed by the firmware, you can switch it off with the [disable_splash](https://www.raspberrypi.org/documentation/computers/config_txt.html#disable_splash) option in *config.txt*.

**Comment by stay26** [comment]
I want to change that rainbow screen with other image. I already disable it in config file.

**Comment by rsta2** [comment]
There is no special support for splash screens in Circle, but you can draw one on your own using the `SetPixel()` method of the class `CScreenDevice`. Have a look at *sample/02-screenpixel* for that. Another possibility is to use the class `C2DGraphics`, which is demonstrated in *sample/41-screenanimations*.

**Comment by stay26** [comment]
Thanks, i will go with `SetPixel()` method.
