### ISSUE TITLE
EMMC log print

### ISSUE THREAD

**Issue by jamesbond67** [rsta2/circle#252]
I want to print system log in cm4 emmc but don't know how to access it via circle.

**Comment by rsta2** [comment]
The EMMC driver writes to the normal `CLogger` system log class, which is enabled in most sample programs, but generates only a few messages by default. If you want more (debug) messages you can enable the define `EMMC_DEBUG2` [here](https://github.com/rsta2/circle/blob/master/addon/SDCard/emmc.cpp#L59).

**Comment by jamesbond67** [comment]
Ok thanks for the help. It worked.
