### ISSUE TITLE
Suggestion ST7789 LCD Driver

### ISSUE THREAD

**Issue by froggestspirit** [rsta2/circle#256]
There's a couple open source drivers for screens like the ST7789, which are popular amongst some portable projects. Is there any chance that something like this could be supported in an example?

**Comment by rsta2** [comment]
There is a new driver for ST7789-based displays and a sample program in [addon/display](https://github.com/rsta2/circle/tree/st7789-display/addon/display) on the *st7789-display* branch. It is working well here.

**Comment by froggestspirit** [comment]
Thank you!! I'll check this one out!

**Comment by froggestspirit** [comment]
I finally got around to testing this, and it works great on one of my displays! I had to use reset pin 27 and DC pin 25. My other setup with the ATTiny controlling the backlight wasn't displaying, but I'm pretty sure that's just me forgetting what pins I had to toggle to have the ATTiny turn it on. Thanks again!!!

**Comment by rsta2** [comment]
Thanks for the info, that the driver is working for you. That's valuable feedback. I will merge the ST7789 support to the *develop* branch soon, so it will be part of the next release.

**Comment by rsta2** [comment]
The ST7789 display support is on the *develop* branch now. The *st7789-display* branch has been deleted.

**Comment by rsta2** [comment]
The ST7789 support has been released with Circle 44.3, so this can be closed.

**Comment by incanus** [comment]
I'm curious where you want to draw the line on addons like this. I have written drivers for the ILI9341 and SH1106 displays as well using Circle and could clean them up and contribute.

**Comment by rsta2** [comment]
It would be great to have drivers for more displays for Circle. So if you want to contribute your drivers, you are invited to do so. Please branch off from the *develop* branch, add the display drivers to *addon/display/* and send a Pull Request. Unfortunately I do not have ILI9341- and SH1106-based displays, so I won't be able to test your code with Circle. That's why you have to do this carefully.

**Comment by ellisgl** [comment]
@incanus I would love to see the SH1106. I tried to get the SSD1306 driver to work for the 1106, without luck.

**Comment by ellisgl** [comment]
@incanus nevermind - I got something working: https://github.com/ellisgl/circle/tree/SH1106-Driver
