### ISSUE TITLE
file+I2S audio project

### ISSUE THREAD

**Issue by flatmax** [rsta2/circle#257]
I am keen to find someone to implement the following project on a Pi :
* Fetch raw audio from a file on a USB drive (FAT16 or FAT32) can be a static stereo, 32 bit 48kHz format for reading from file to make it easy.
* Move through the audio file forwards or backwards depending on the state of a GPIO pin.
* Playback through an Audio Injector Zero or Stereo board connected on the I2S bus. Simply pipe that audio as it is read over the I2S lines.

I can help with any necessary info on the Audio Injector soundcard.

Anyone interested ?

**Comment by rsta2** [comment]
This is not a real issue and nobody responded. I don't think, there will be an answer any more. That's why I close this.
