### ISSUE TITLE
Could MCP300x support provide an API for the "raw" value from the adc?

### ISSUE THREAD

**Issue by diyelectromusic** [rsta2/circle#263]
Unless I'm missing something, I believe the MCP300x support appears to only return the absolute measured (scaled) voltage from the analog inputs.

Could a method be added to return the raw digital value being read?  This mirrors what many might expect to happen if they are used to programming microcontrollers (for example from analogRead with Arduino), where you expect the analog to digital conversion to return the digital value from the conversion not a scaled analog value.

Many thanks for circle, this is amazing work!

**Comment by rsta2** [comment]
Yes, of course this can be added. I will try to provide a version for test until weekend. Thanks for appreciating Circle!

**Comment by rsta2** [comment]
The updated version is on the *develop* branch.

**Comment by diyelectromusic** [comment]
Look's perfect!  Many thanks :)

**Comment by rsta2** [comment]
Reading the raw values is now supported in the Circle release 44.3, so this can be closed.
