### ISSUE TITLE
FATFS Addon vs Circle FATFS ?

### ISSUE THREAD

**Issue by Buanderie** [rsta2/circle#271]
Hello.
What is the difference between the FATFS code already present in Circle, and the code provided by the FATFS addon ?
The examples provided with both code seems to demonstrate the same functionality...

**Comment by rsta2** [comment]
The FAT filesystem module in lib/fs/fat/ had been implemented, when I didn't know the FatFs library (now in addon/fatfs/) yet. For new implementations the latter solution is recommended, because it has more features (e.g. access to subdirectories, long filenames) and a better performance.

**Comment by Buanderie** [comment]
I see. Thanks for clarifying !
