### ISSUE TITLE
Problems with keyboard USB 1.1

### ISSUE THREAD

**Issue by jsanchezv** [rsta2/circle#28]
Hello René,

I'm testing the new code in develop branch. I've found as issue with the LED handling with a keyb Logitech K120 keyboard that not exist when I use a HP keyb (USB 2.0).

I've found another problem with new gamepad code while using a Sony DualShock Sixaxis for PS3 (original, not clone). Both errors are shown at boot:

00:00:00.71 usbdev0-1: Device ven424-9514, dev9-0-2 found
00:00:00.72 usbdev0-1: Interface int9-0-1 found
00:00:00.72 usbdev0-1: Function is not supported
00:00:00.73 usbdev0-1: Interface int9-0-2 found
00:00:00.73 usbdev0-1: Using device/interface int9-0-2
00:00:02.94 usbdev0-1: Device ven424-ec00 found
00:00:02.94 usbdev0-1: Using device/interface ven424-ec00
00:00:03.11 usbdev1-2: Device ven46d-c31c found
00:00:03.12 usbdev1-2: Interface int3-1-1 found
00:00:03.12 usbdev1-2: Using device/interface int3-1-1
00:00:03.13 usbdev1-2: Interface int3-0-0 found
00:00:03.13 usbdev1-2: Using device/interface int3-0-0
00:00:03.30 usbdev1-3: Device ven46d-c03e found
00:00:03.30 usbdev1-3: Interface int3-1-2 found
00:00:03.31 usbdev1-3: Using device/interface int3-1-2
00:00:03.49 usbdev1-5: Device ven54c-268 found
00:00:03.49 usbdev1-5: Interface int3-0-0 found
00:00:03.50 usbdev1-5: Using device/interface int3-0-0
00:00:03.55 smsc951x: MAC address is B8:27:EB:F6:EA:B3
00:00:03.56 usbhub: Port 1: Device configured
00:00:03.62 dwhci: Transaction failed (status 0xA)
00:00:03.63 usbpad: Cannot get HID report descriptor
00:00:03.63 usbhub: Port 2: Device configured
00:00:03.69 usbhub: Port 3: Device configured
00:00:03.75 dwhci: Transaction failed (status 0xA)
00:00:03.75 usbpad: Cannot get HID report descriptor
00:00:03.76 usbhub: Port 5: Cannot configure device
00:00:03.76 dwroot: Device configured

I have connected Logitech keyb, a mouse and PS3 DualShock.

**Comment by rsta2** [comment]
Hi José Luis,

there were two problems in the USB gamepad and the USB HID driver:

* The HID report descriptor was requested from the USB device, not from the interface. This did not work with some devices.

* The USB HID driver did statically take the first endpoint in the configuration descriptor and expected it to be an interrupt in endpoint. Some gamepads have additional endpoints which are located before the interrupt in endpoint in the descriptor. Now the HID driver searches for the right endpoint.

Both problems have been fixed on the *develop* branch. There has not been a problem on *master* branch.

Thank you!
