### ISSUE TITLE
Can I use the standard C++ STL libraries? Do I need to use a custom allocator?

### ISSUE THREAD

**Issue by zolbatar** [rsta2/circle#284]
As the title suggests, would the normal STL containers work? Have they been patched to use the heap allocation in Circle? Or would I need to write my own allocator and subclass them?

I have this feeling that they won't work properly except where the memory is already allocated like on the local stack.

**Comment by rsta2** [comment]
You can use the [circle-stdlib](https://github.com/smuehlst/circle-stdlib) project, if you need the standard C++ library. It is based on Circle and includes it as a submodule. This is the intended way to do this. CIrcle by itself does not support STL containers.

**Comment by rsta2** [comment]
I think this can be closed?
