### ISSUE TITLE
Example on how to read GPIO as input

### ISSUE THREAD

**Issue by probonopd** [rsta2/circle#292]
It would be nice to have an example on how to read a GPIO as an input.

For example, how to read whether GPIO18 is high or low, and how to react on state changes (interrupt?).

**Comment by rsta2** [comment]
Generating interrupts from GPIO lines is shown in [sample/09-softserial](https://github.com/rsta2/circle/blob/master/sample/09-softserial/softserial.cpp). `m_RxDPin.Read()` returns the current input level (`LOW` (0) or `HIGH` (1)).
