### ISSUE TITLE
Does this project supports xhci that is inside SoC? 

### ISSUE THREAD

**Issue by Marcinoo97** [rsta2/circle#311]
Pi 4 has 3 usb controllers, 2 of them are xhci(soc and VLI on pcie) and one dwc2 one. Is use of xhci inside SoC supported for type c port in this project? or will you just force people to use dwc2 for type c port?

**Comment by rsta2** [comment]
For completeness: On the Raspberry Pi 4 Circle normally uses the external xHCI controller, which is connected to PCIe. To use the internal xHCI controller one has to define the system option [USE_XHCI_INTERNAL](https://github.com/rsta2/circle/blob/master/include/circle/sysconfig.h#L182). The DWC OTG USB controller is not supported on this RPi model.
