### ISSUE TITLE
SQLite3 example?

### ISSUE THREAD

**Issue by froggestspirit** [rsta2/circle#328]
I was attempting to compile sqlite3 for use with circle, though has no luck. I'm not sure if this might be something useful for others if it were to be supported?

**Comment by rsta2** [comment]
Have you tried to use the [circle-stdlib project](https://github.com/smuehlst/circle-stdlib) for the build? It provides C-standard-lib support for Circle and it's more likely to work for porting projects, which are targeted for UNIX/Linux environments.

**Comment by rsta2** [comment]
I did a quick hack and some functions of SQLite3 already work (in QEMU):

![screenshot](https://user-images.githubusercontent.com/9377920/204509520-9411d839-cd3d-49d4-b07d-c26acbd9b9ea.png)

If you want to try it, extract the attached archive into the directory *samples/06-sqlite/* of the cloned circle-stdlib project. Put the files from [this SQLite3 source archive](https://sqlite.org/hp1.html) into the same directory and apply the patches in *sqlite.diff*. After configuring circle-stdlib for example with `configure -r 3 -p aarch64-none-elf- --no-cpp` and building it with `make -j`, go to the *samples/06-sqlite/* directory and enter `make -j`. You will get some warnings, which are not critical.

*func.c* contains the stubs for functions, which are not implemented by circle-stdlib. Most functions in this file are not implemented yet. Saving a database to a file does not work yet.

[06-sqlite.zip](https://github.com/rsta2/circle/files/10112295/06-sqlite.zip)

**Comment by froggestspirit** [comment]
Thank you! I'll give that a try this afternoon

**Comment by rsta2** [comment]
@froggestspirit Did this work for you?

**Comment by froggestspirit** [comment]
Yes, the example you posted worked! I was working on trying to get file support working with the sd card, but haven't found the time to get back to that yet.

**Comment by froggestspirit** [comment]
I spent some time trying to get some file reading/writing working, but the closest I got was porting a SQL logger for arduino (which doesn't really support querying). I'm thinking that this needs a custom VFS? I grabbed the test_demovfs from the sqlite site, and tried adjusting it to use the fopen, fread, fwrite, etc. I've attached what I got here, but most of what I tried results in the SQLITE_CANTOPEN (error code 14).
[06-sqlite.zip](https://github.com/rsta2/circle/files/10203331/06-sqlite.zip)

**Comment by rsta2** [comment]
I also did some debugging with QEMU here. I think the problem has to do with the `stat()` function, which always returns an error. I guess, it is not supported by *circle-newlib*. Also the file names are a problem, because they need the prefix `"SD:"` to access the SD card, which is not UNIX standard. SQLite cannot handle this. Unfortunately I'm not familiar with SQLite and it takes time to understand, what it does. Perhaps I will have another look at this after Xmas when my current project has reached a reasonable state.

**Comment by rsta2** [comment]
I already got most features running. You can have a look on it [here](https://github.com/rsta2/sqlite). The main problem were the functions `stat()`, `fstat()` and `fcntl()`, which exist in the circle-newlib project, but are only stubs, which always return an error. I replaced these functions with own versions in *func.c*. `fcntl()` cannot be really implemented for record locking, but always returns success now.

Unfortunately there is still a problem. Under some conditions SQLite reports a "malformed schema on disk" after creating a database. This does not happen, when creating the database in memory and writing it to disk with `.save` then. This problem has still to be analyzed.

**Comment by froggestspirit** [comment]
Thank you! I have some time off over the holidays, I should be able to test it out

**Comment by rsta2** [comment]
You are welcome. In the meantime I have found the "malformed schema" problem. `fsync()` needs to be implemented. I did this in a quick hack and the problem was gone. For a real solution we'll need more time and modifications in circle-newlib. I will let you know, when it's fixed.

**Comment by rsta2** [comment]
The project has been updated. Thanks to @smuehlst there is additional support from the circle-stdlib project now. `fsync()` is implemented. I did some tests and currently I'm not aware of any problems. It is currently not clear, if SQLite opens the same file multiple times with different file descriptors. This is not supported by FatFs and could cause problems. I still have to check, if this happens.

**Comment by rsta2** [comment]
@froggestspirit My impression is, that everything, which can be supported, is working now. Also SQLite does not open the same file multiple times. BUT, there are open questions on the internal function of SQLite and together with circle-stdlib and the FatFs file system module. It is not clear, why SQLite does not work, when `fsync()` is not implemented on a single user system like this one, and why it does not work, when `fsync()` is called inside `fstat()` to update the file information, before it is fetched to be returned in the `struct stat`.

Again, SQLite seems to work in the current state of the repo [sqlite](https://github.com/rsta2/sqlite), but it would possibly take much more time to answer the given questions. Unfortunately we don't have the time to analyze this further and can only present this current state. It is currently not planned to develop this further, and it is likely that the repo *sqlite* will be removed from my project space in some weeks.

**Comment by froggestspirit** [comment]
Thanks! I just downloaded a zip of the repo. I should have some more time to look at it soon

**Comment by smuehlst** [comment]
@froggestspirit If you can find out more about the strange behavior regarding `fsync()` in SQLite I would be interested. I currently don't have time to investigate this myself, but if there are insights that help improve the FatFS-based file operations in circle-stdlib they are certainly welcome.

**Comment by froggestspirit** [comment]
I did a quick test with this, instead of using the CLI (since I'm aiming to use this for a sort of mp3 player), I ran some commands to create a table, insert a column, then read what's in that table, and re-insert the same records (multiplied by 3). It looks like it's working!

**Comment by rsta2** [comment]
OK, I suppose, it is working. So this can be closed. The [sqlite repo](https://github.com/rsta2/sqlite) will remain as an example and for testing purposes.
