### ISSUE TITLE
add ability to clear raw keyboard handler

### ISSUE THREAD

**Issue by incanus** [rsta2/circle#344]
Thanks as ever @rsta2. What do you think about adding the ability to clear the raw keyboard handler? I have been using this for some time on my own project and am wondering why it doesn't exist in the library. 

```c
void RegisterKeyStatusHandlerRaw (TKeyStatusHandlerRaw *pKeyStatusHandlerRaw,
                                  boolean bMixedMode = FALSE);

void ClearKeyStatusHandlerRaw() { m_pKeyStatusHandlerRaw = 0; }
```

**Comment by rsta2** [comment]
I added a similar method `UnregisterKeyStatusHandlerRaw()` on the *develop* branch. The term "unregister" has been already used somewhere else in Circle, so for being homogeneous. Thanks for the hint!

**Comment by rsta2** [comment]
This feature is in Circle 45.2 now.
