### ISSUE TITLE
Porting to different platforms

### ISSUE THREAD

**Issue by mardab** [rsta2/circle#358]
I am aware of major differences between BCM27xx and other platforms, especially in uncore, and as such before attempting a port or a similar library, I'd like to ask whether you'd ever be interested with such port, and whether should it be eventually submitted for inclusion under one umbrella upon reaching certain maturity milestone(s).

Alternatively, I'd like to know your opinion on at least partially source-compatible implementation for different SoC platform.

**Comment by rsta2** [comment]
I want to stay with the Raspberry Pi platform. I don't think, Circle is very well suited to support multiple platforms. One would have to insert intermediate software layers to switch between the different drivers, which are often accessed directly by the applications. This contradicts the wish, to keep everything as simple as possible for performance and easy management and testing.
