### ISSUE TITLE
Application specific cmdline.txt options

### ISSUE THREAD

**Issue by toptensoftware** [rsta2/circle#377]
Is there a way for an circle application to have its own custom cmdline.txt parameters?

Use case:  I've got an app that runs on multiple devices, but doesn't need SD card access.  Each needs to be configured slightly differently (basically a different I2C address for each one) and cmdline.txt would be an easy way to configure this.

What if `CKernelOptions` kept track of anything it didn't recognize as a separate string so the app could get anything left over?

(again I'm happy to implement this after hearing your thoughts)

**Comment by rsta2** [comment]
I will provide a solution for this, as suggested. `CKernelOptions` will save all values for options, it does not know and offer the following new methods:

```
const char *GetAppOptionString (const char *pOptionName);
unsigned GetAppOptionDecimal (const char *pOptionName);
```

**Comment by rsta2** [comment]
Done.

**Comment by toptensoftware** [comment]
Awesome - thanks!
