### ISSUE TITLE
does the VCHIQ audio service support PWM on the pi zero?

### ISSUE THREAD

**Issue by benmcevoy** [rsta2/circle#382]
Hi,

sorry not really an issue but a  quick yes/no question.

I am playing with the /addon/vc4/sound/sample

Is it possible to route the audio to PWM and pins 12,13?

I have set

#define USE_PWM_AUDIO_ON_ZERO

and only get output on HDMI.

I am guessing this is not supported?

Thanks

**Comment by rsta2** [comment]
No, this is not supported. The option `USE_PWM_AUDIO_ON_ZERO` only works with the PWM sound hardware driver with the class `CPWMSoundBaseDevice`.

**Comment by rsta2** [comment]
I think, this can be closed.
