### ISSUE TITLE
I2CSlave and broadcast to general call address

### ISSUE THREAD

**Issue by toptensoftware** [rsta2/circle#383]
It seems the I2C Slave support in circle doesn't receive general call messages (ie: messages sent from master to address 0).  [see here](https://www.i2c-bus.org/addressing/general-call-address/)

If I open the slave on address 0 I get the broadcast messages, but then not the addressed ones?

Is it possible to get this to work with both broadcast and addressed messages?

**Comment by rsta2** [comment]
Unfortunately this is not supported by the I2C slave hardware in the RPi and will not work.

**Comment by rsta2** [comment]
I will add a note.

**Comment by rsta2** [comment]
The note is in the header file on the *develop* branch and will be added to the docs later.
