### ISSUE TITLE
aarch64-none-elf-g++: fatal error: '-fuse-linker-plugin', but liblto_plugin.so not found compilation terminated.

### ISSUE THREAD

**Issue by AlexandreBourrieau** [rsta2/circle#390]
Hello,

I have some some difficulties to make file using WSL on windows.

I have : 
 - installed WSL2 + ubuntu 22.04.6 ;
 - Update & upgrade
 - Dowloaded "arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf" and extract it
 - Copy all the file from arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf/bin to /usr/bin
 - added the path "arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf/libexec/gcc/aarch64-none-elf/12.2.1" to my env

But when i run ./makeall clean I got : 

```
 CLEAN  /mnt/f/Dev Elec/Raspberry/DAQ_/circle-master/tools
aarch64-none-elf-g++: fatal error: '-fuse-linker-plugin', but liblto_plugin.so not found
compilation terminated.
```
But libto_plugin.so is in the path... (in arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf/libexec/gcc/aarch64-none-elf/12.2.1) so it weird it cannot be found ??..

I tried to make a symbolic link but it does not work too... : 

Can someone help me please ? Thanks you !

**Comment by rsta2** [comment]
Personally I never used WSL, but I've heard, that filenames and paths, which contain white spaces, may cause such problems. You could try to put the toolchain and the Circle project into directories with paths, which do not contain white spaces and start again.

**Comment by AlexandreBourrieau** [comment]
Thanks I will try that.

**Comment by AlexandreBourrieau** [comment]
Hello, not really but I used another toolchain in windows with Pycharm Clion and mgywin64 and it worked. I can compile 64 and 32bits. But I needed to use a old toolchain because with more recent one I got same error...
Thanks you for your help anyway ;)

**Comment by rsta2** [comment]
Thanks for info.
