### ISSUE TITLE
Cross toolchain on Windows needs modification slightly of CFLAGS in Rules.mk

### ISSUE THREAD

**Issue by meesokim** [rsta2/circle#4]
Windows 8.1 Mingw environment,

Rules.mk CFLAGS may cause an compile error like the following.

arm-none-eabi-g++ -march=armv5 -mtune=arm1176jzf-s -Wall -Wno-psabi -fsigned-char -fno-builtin -nostdinc -nostdlib -undef -D__circle__ -I ../include -I ../addon -O  -fno-exceptions -fno-rtti -std=c++0x -c -o synchronize.o synchronize.cpp
C:\Users\Miso\AppData\Local\Temp\ccBIvGL4.s: Assembler messages:
C:\Users\Miso\AppData\Local\Temp\ccBIvGL4.s:27: Error: selected processor does not support ARM mode `cpsid i'
C:\Users\Miso\AppData\Local\Temp\ccBIvGL4.s:79: Error: selected processor does not support ARM mode `cpsie i'
make: *** [synchronize.o] Error 1

I could fix the compile error with change of CFLAGS as the following.

CFLAGS	+= -march=armv6j -mfloat-abi=hard -mtune=arm1176jzf-s -Wall -Wno-psabi -fsigned-char -fno-builtin -nostdinc -nostdlib \
	   -undef -D__circle__ -I $(CIRCLEHOME)/include -I $(CIRCLEHOME)/addon -O #-DNDEBUG

There will be no more compile error on Windows.

**Comment by rsta2** [comment]
I have changed this as suggested. Thanks!
