### ISSUE TITLE
Support for touchscreens with additional reports in HID descriptor

### ISSUE THREAD

**Issue by jackhumbert** [rsta2/circle#418]
I've been using a [Waveshare touchscreen](https://www.waveshare.com/wiki/9.3inch_1600x600_LCD) that seems to have an additional report in its descriptor (a vendor-defined one), which causes the size of the expected report to be too large. I got it working by [only increasing `nBitOffset` when `nReportID` is `1`](https://github.com/jackhumbert/circle/commit/636ef7ad534ed9681fe602613e7e36d369e8bfb9):

```diff
--- a/lib/usb/usbtouchscreen.cpp
+++ b/lib/usb/usbtouchscreen.cpp
@@ @@ boolean CUSBTouchScreenDevice::DecodeReportDescriptor (const u8 *pDesc, unsigned
                 if (ucItem == HID_INPUT)
                {
-                       nBitOffset += nReportCount * nReportSize;
+                       if (nReportID == 1) {
+                       {
+                               nBitOffset += nReportCount * nReportSize;
+                       }
                }
        }
```

Is there a more complete way to handle this? I also have the [full descriptor of the touchscreen here](https://gist.github.com/jackhumbert/da6e3526073093a3633ed0c184bacf52), generated from [wedhid-explorer](https://nondebug.github.io/webhid-explorer/).

Thanks for all your work on Circle!

**Comment by rsta2** [comment]
Diving into a HID parser (again) is always a bit tricky and will need some 
time. Can you please send the HID report descriptor as a hex-dump, so that I 
can use my own tool for decoding it. Thank you, also for appreciating Circle!

**Comment by jackhumbert** [comment]
Gotcha! Here's the hex dump of the descriptor:

> 05 0D 09 04 A1 01 85 01 09 22 A1 02 05 0D 95 01
75 06 09 51 15 00 25 3F 81 02 09 42 25 01 75 01
95 01 81 02 75 01 95 01 81 03 05 01 75 10 55 0E
65 11 09 30 26 00 10 35 00 46 9B 14 81 42 09 31
26 00 10 46 9A 0B 81 42 C0 05 0D 09 22 A1 02 05
0D 95 01 75 06 09 51 15 00 25 3F 81 02 09 42 25
01 75 01 95 01 81 02 75 01 95 01 81 03 05 01 75
10 55 0E 65 11 09 30 26 00 10 35 00 46 9B 14 81
42 09 31 26 00 10 46 9A 0B 81 42 C0 05 0D 09 22
A1 02 05 0D 95 01 75 06 09 51 15 00 25 3F 81 02
09 42 25 01 75 01 95 01 81 02 75 01 95 01 81 03
05 01 75 10 55 0E 65 11 09 30 26 00 10 35 00 46
9B 14 81 42 09 31 26 00 10 46 9A 0B 81 42 C0 05
0D 09 22 A1 02 05 0D 95 01 75 06 09 51 15 00 25
3F 81 02 09 42 25 01 75 01 95 01 81 02 75 01 95
01 81 03 05 01 75 10 55 0E 65 11 09 30 26 00 10
35 00 46 9B 14 81 42 09 31 26 00 10 46 9A 0B 81
42 C0 05 0D 09 22 A1 02 05 0D 95 01 75 06 09 51
15 00 25 3F 81 02 09 42 25 01 75 01 95 01 81 02
75 01 95 01 81 03 05 01 75 10 55 0E 65 11 09 30
26 00 10 35 00 46 9B 14 81 42 09 31 26 00 10 46
9A 0B 81 42 C0 05 0D 09 22 A1 02 05 0D 95 01 75
06 09 51 15 00 25 3F 81 02 09 42 25 01 75 01 95
01 81 02 75 01 95 01 81 03 05 01 75 10 55 0E 65
11 09 30 26 00 10 35 00 46 9B 14 81 42 09 31 26
00 10 46 9A 0B 81 42 C0 05 0D 09 22 A1 02 05 0D
95 01 75 06 09 51 15 00 25 3F 81 02 09 42 25 01
75 01 95 01 81 02 75 01 95 01 81 03 05 01 75 10
55 0E 65 11 09 30 26 00 10 35 00 46 9B 14 81 42
09 31 26 00 10 46 9A 0B 81 42 C0 05 0D 09 22 A1
02 05 0D 95 01 75 06 09 51 15 00 25 3F 81 02 09
42 25 01 75 01 95 01 81 02 75 01 95 01 81 03 05
01 75 10 55 0E 65 11 09 30 26 00 10 35 00 46 9B
14 81 42 09 31 26 00 10 46 9A 0B 81 42 C0 05 0D
09 22 A1 02 05 0D 95 01 75 06 09 51 15 00 25 3F
81 02 09 42 25 01 75 01 95 01 81 02 75 01 95 01
81 03 05 01 75 10 55 0E 65 11 09 30 26 00 10 35
00 46 9B 14 81 42 09 31 26 00 10 46 9A 0B 81 42
C0 05 0D 09 22 A1 02 05 0D 95 01 75 06 09 51 15
00 25 3F 81 02 09 42 25 01 75 01 95 01 81 02 75
01 95 01 81 03 05 01 75 10 55 0E 65 11 09 30 26
00 10 35 00 46 9B 14 81 42 09 31 26 00 10 46 9A
0B 81 42 C0 05 0D 09 56 55 00 65 00 27 FF FF FF
7F 95 01 75 20 81 02 09 54 25 7F 95 01 75 08 81
02 85 02 09 55 25 0A B1 02 06 00 FF 09 C5 85 03
15 00 26 FF 00 75 08 96 00 01 B1 02 C0 06 00 FF
09 01 A1 01 85 09 09 01 15 00 26 FF 00 95 3F 75
08 81 02 09 01 15 00 26 FF 00 95 04 75 08 91 02
C0

What tool do you use for decoding?

**Comment by rsta2** [comment]
Thank you! I found this tool:

http://eleccelerator.com/usbdescreqparser/

Let me analyze this.

**Comment by rsta2** [comment]
There is an update on the *develop* branch, only slightly different from the one, you have suggested. It only considers the first found Report ID and ignores all others. The touchscreen driver was only able to handle one Report ID already, but did not ignore the other ones. Can you please test this again with your touchscreen. Thank you!

**Comment by jackhumbert** [comment]
Just tested it out - that works perfectly. Thanks!

**Comment by rsta2** [comment]
You are welcome, and thanks for the comprehensive report!

**Comment by rsta2** [comment]
This modification is in Circle 46.
