### ISSUE TITLE
Question: Waveshare 5'' DSI display support?

### ISSUE THREAD

**Issue by bogdanm** [rsta2/circle#422]
This is not a bug, just a question: did anyone try to run Circle with https://www.waveshare.com/5inch-dsi-lcd.htm and got both the display and the touch working? Thank you.

**Comment by rsta2** [comment]
Unfortunately I don't think, that this display will work with Circle. The two 
device tree overlays, which have to be loaded for Raspberry Pi OS according to 
the wiki entry of the display, are not available for Circle. The display is 
supported by Linux, not by the firmware itself, which would be required.

**Comment by bogdanm** [comment]
Thanks for the quick resonse!
