### ISSUE TITLE
Problem with multicore support and last firmware

### ISSUE THREAD

**Issue by jsanchezv** [rsta2/circle#43]
Hi Rene,

From last firmware update, the secondary CPUs don't start correctly. The reason is this change:

https://github.com/raspberrypi/tools/pull/76

I've applied this small modification to multicore.cpp:

write32 (ARM_LOCAL_MAILBOX3_SET0 + 0x10 * nCore, (u32) &_start_secondary);
 `asm volatile ("sev");`

So, the CPUs are starting again.

Best regards

**Comment by rsta2** [comment]
I have fixed this as suggested. Thanks!
