### ISSUE TITLE
CPU Frequency

### ISSUE THREAD

**Issue by koparasy** [rsta2/circle#44]
Hi. 

I am executing a cpu heavy application which uses circle. The application iteratively performs some logistics ( reading inputs, allocating memory) and then it turns into a computative intensive benchmark. I want to boot raspberry PI with a low frequency ( 600Mhz ) perform all the logistics in the low frequency ( 600Mhz) and then turn frequency on the Max ( 1200 Mhz).   
On a pseudo code this looks like : 

Boot....
Application:
while ( True ){
        setFreqToLow(600)
        PerformLogistics()
        setFreqToHight(1200)
        PerformComputations()
}

When I boot PI using the fast option it  boots with the high frequency ( 1200 ) and then it toggles between 600Mhz-1200 Mhz normally. When I dont use the "fast" option the PI boots on the low (600Mhz ) frequency but it cannot set the high frequency afterwards. The `CCPUThrottle::SetSpeed(CPUSpeedMaximum,True)` returns "0". 

Any idea why this happens? Thank you very much in advance.

**Comment by rsta2** [comment]
CCPUThrottle::SetSpeed() returns the speed setting which was previously in effect before the call or CPUSpeedUnknown on error. The return value is defined as follows:

```
enum TCPUSpeed
{
	CPUSpeedLow,
	CPUSpeedMaximum,
	CPUSpeedUnknown
};
```

So a return value of zero means CPUSpeedLow, which should be right. You can call CCPUThrottle::GetClockRate() to check, if the wanted clock rate is really in effect.
