### ISSUE TITLE
FIQ support on RPI Zero 2

### ISSUE THREAD

**Issue by JaRoLoz** [rsta2/circle#442]
Hi, I'm thinking on getting a Raspberry Pi Zero 2 for a project of mine, but a question emerged when reading the [FIQ interrupt dcoumentation](https://circle-rpi.readthedocs.io/en/46.0/basic-system-services/interrupts.html), where it says that the Raspberry pi 5 doesn´t currently support FIQs, but the pi zero does. Does this mean that the pi zero 2 can use an FIQ or not?

**Comment by rsta2** [comment]
The FIQ is supported on the Raspberry Pi Zero 2 W.

**Comment by JaRoLoz** [comment]
Great! tssm for the info

**Comment by rsta2** [comment]
You are welcome. I think, this can be closed.
