### ISSUE TITLE
About memory management on CM4

### ISSUE THREAD

**Issue by AlexandreBourrieau** [rsta2/circle#458]
Hello,

I would like to have some information on what is explained in the documentation regarding memory allocation.

From the doc : 

```
Circle can currently handle up to 2 GBytes of high memory, which should be
enough for common bare metal applications.
```

But after you say : 
```
If your Raspberry Pi 4 has 4 GBytes SDRAM, the highest 1 GByte memory region is unused. This is necessary, because
memory above the 3 GByte boundary may require a specific DMA-handling, which is not implemented so far.
```

=> So if I understand well, with a RPI CM4 4GB, I can use 1GB from HEAP_BELOW and 2GB from HEAP_HIGH ? So a total of 3GB ?

Second question : Can we allocate continuous space memory of 3 GB like using HEAP_ANY ? Or do I need to allocate one space of 1GB for the first GB and anothe space of 2GB for the rest ?

Thanks you very much !

**Comment by rsta2** [comment]
> => So if I understand well, with a RPI CM4 4GB, I can use 1GB from
> HEAP_BELOW and 2GB from HEAP_HIGH ? So a total of 3GB ?

Yes, but HEAP_LOW is less than 1 GB, because some memory is already used for 
the kernel image, by the firmware and for peripherals. You can call 
CMemorySystem::Get()->GetHeapFreeSpace(HEAP_LOW) to determine the available 
free space in HEAP_LOW.

> Second question : Can we allocate continuous space memory of 3 GB like using
> HEAP_ANY ? Or do I need to allocate one space of 1GB for the first GB and
> anothe space of 2GB for the rest ?

The second statement is true. It's not possible to allocate a continuous block 
of 3 GB.

**Comment by AlexandreBourrieau** [comment]
Thanks you !
