### ISSUE TITLE
Simple Request: Remote IP Address Accessible from TFTPDaemon

### ISSUE THREAD

**Issue by davefilip** [rsta2/circle#514]
Rene,

I have a simple request for a very small change with CTFTPDaemon, with a few ways to address.  I appreciate that this might not be a priority, but you agree, would appreciate getting into the Develop code branch.

The gist is that I am writing my own CTFTPServer -- which handles all of the file I/O -- but I don't have access to the remote (requesting) socket.

Why do I need that?  I am using TFTP because it is a simple, fast, very low overhead protocol to transfer files between Circle nodes.  I have that working, but I would like to implement some very basic security around IP address, since TFTP is completely open.

Gist is, I want to permit access from one of the "cluster" nodes (Circle nodes that communicate amongst themselves and can currently send commands on each other), or an external node that is in a "whitelist" of IPs.  Any other IP address, I want to deny access.

Although CFTPServer (or rather my replacement class with a slightly different name) inherits from CTFTPDaemon, the request socket (*m_pRequestSocket) is private, and therefore not accessible from an inherited class.  If it were accessible, I could call m_pRequestSocket->GetForeignIP() to get the remote IP address.

The easiest way to do this -- and one which would solve my need -- would be simply to make m_pRequestSocket protected, which would make it accessible to any class the inherited CFTPDaemon.  If you could accept this change, I would be grateful.

The other option is to add a GetRemoteSocket() or GetRemoteIP() function to CFTPDaemon.  A few more lines of code in either case.

Please advise if you would agree to changing m_pRequestSocket in tftpdaemon.h from private to protected (the easiest method).  Otherwise, if you disagree with exposing the socket to an inherited classes, let me know if a GetRemoteIP() method could be added (just a few lines of code that even a novice like me could send you).

Why don't I just make the change myself on my end?  Because I don't want to have to hand edit Circle code every time I upgrade to a new release / step.

Please advise as to your thoughts on this.

Cheers,

Dave.

**Comment by davefilip** [comment]
UPDATE: Actually, after doing a quick test, it appears that I really need m_pTransferSocket to be changed from private to protected.

Logically I assumed it would be m_pRequestSocket ... I thought that would be the socket receiving the request from the remote computer? ... but no, that returns a foreign IP address of 0.0.0.0.  Not sure why.

Making m_pTranserSocket protected and calling m_pTransferSocket->GetForeignIP() appears to retrieve the correct remote IP.

Sorry for the confusion!

Dave.

**Comment by rsta2** [comment]
I thought about this. I see the problem, that the m_pTransferSocket is only 
available, when a transfer is running and will be deleted after the transfer. 
You could use use the UpdateStatus() callback to wait for a transfer and then 
check the transfer socket, but what do you want to do, if the foreign IP 
address is not allowed? The transfer is already running at this point.

My suggestion would be another virtual method als a callback, which can be 
overridden:

virtual boolean IsTransferAllowed (const CIPAddress &rForeignIP)
{
	return TRUE;
}

By default so any client is allowed, but with your own implementation in an 
derived custom TFTP server class, you can implement an access control, based 
of the IP address with this. Perhaps this method could also receive the 
requested transfer direction (read or write) and the filename.

What do you think about this?

BTW. The m_pRequestSocket is bound to the TFTP port 69 and can receive packets 
from any sender with ReceiveFrom(), so the foreign address is not valid.

Rene

**Comment by rsta2** [comment]
I have implemented both the suggested virtual method `IsAccessAllowed()` (changed name and extended parameter list) and the protected member variables. It's on the *develop* branch.

**Comment by davefilip** [comment]
Great, thanks, I’ll take a look and let you know if this works for my use case.

As always, thanks for the incredibly fast response.

**Comment by davefilip** [comment]
Rene,

OK, I have another interesting challenge, related to TFTP access, for which I believe I can easily code a work-around, but curious if you have another idea as to how this should work?

Summary is whether you will permit me to modify the CString m_Filename, which is the file being requested, from the IsAccessAllowed() function before the file is opened.

If there is an easy answer to this, please let me know.  Otherwise, because I know you like use cases, vs. merely hypotheticals, I am providing my use case here in detail.

Long answer for my use case is that -- as I have alluded to previously -- I am encoding access into the filename for "cluster authorization".  Therefore, for example, to access a file named alpha.txt in the user's UFD (User File Directory) on another node, I would make a TFTP request for:

    //alpha.txt

using the '//' prefix to indicate that cluster authorization is required.  My operating system code, when it sees the '//' prefix before a filename, expands that to something like:

    //coloros:DFILIP:3610C84C/alpha.txt

by adding the local node name (in this case **coloros**) and my username (**DFILIP**) and a token (**3610C84C**), followed by a slash (**/**), and then the actual filename..

On the remote end -- TFTP server -- the node name is verified by the known IP address for that node, and the token -- which rotates every minute -- is also verified.  I am doing this verification in the IsAccessAllowed() function in the TFT server.  If either are incorrect, I return false, and the transfer is aborted.  If both are correct, I return true.

However, the real filename does not -- of course -- contain the authorization between the '//' and '/', so it has to be removed before opening the file.  In addition, files are relative to the user's UFD (User File Directory), in this case /MFD/DFILIP (/MFD is the Master File Directory, which is the parent of all UFDs).  Therefore, within the IsAccessAllowed() function of the TFTP server, assuming all of the verifications are successful, the real filename then becomes:

    /MFD/DFILIP/alpha.txt

So within the IsAccessAllowed() function of the TFTP server, I am updating the CString m_Filename to (in this example):

    /MFD/DFILIP/alpha.txt

And if I print the CString m_Filename within the IsAccessAllowed(), that is what it displays.

However, when the function FileOpen() is called, m_Filename instead becomes:

SD:///coloros:DFILIP:3610C84C/alpha.txt

Which obviously can't be opened, because it incudes the authorization parts (node name, user name, and token).

So, is there a proper way for me to modify the m_Filename in the IsAccessAllowed() function?  Or do I need to create a new variable to store the modified filename and then modify the FileOpen function to use that instead?

The alternative would be to add my authorization logic to FileOpen() and FileCreate(), but then I am duplicating code, or at the very least duplicating processing if I put that logic in a new function.  What is not clear is why I cannot modify m_Filenme in IsAccessAllowed() -- since it is a protected variable -- and not have the modification passed to FileOpen() and FileCreate().

Hopefully this makes sense.  And as I said, I think I can work around this, but it is just circumventing how I think you expect this to work, and in either case means that I simply ignore the *pFileName passed to FileOpen() and FileCreate().  Therefore, if I can properly modify m_Filename in IsAccessAllowed(), then I can keep the code clean.

Please advise.  And no, I'm not asking you to do a lot of work for my specific use case, just whether or not there is a proper way for me to alter the filename, in addition to checking for valid access, in the IsAccessAllowed() function so that it gets passed to FileOpen() and FileCreate().  If there is no simple or clean answer, then I can probably figure out a work-around.

Cheers,

Dave.
![TFTPFileNames](https://github.com/user-attachments/assets/13096ce9-c607-4a82-bb9b-74f5e055b4f4)

**Comment by rsta2** [comment]
Dave, the recommended way to handle this in my opinion is, to use your own implementation of `FileOpen()` and `FileCreate()` and to manipulate the received file name there. You can copy the files *addon/tftpfileserver/tftpfatfsfileserver.\** into your own project for this purpose and modify them there. `IsAccessAllowed()` can still be used for access control.

Rene

**Comment by davefilip** [comment]
Thanks Rene!  I do have my own FileOpen() and FileCreate() methods, but was trying to prevent having to manipulate the filename in those two places, as well as in IsAccessAllowed().  Otherwise, it might make sense to not use IsAccessAllowed() and just put all of the logic in FileOpen[Create].

But I understand, you don’t want IsAccessAllowed() to modify the filename, even though you did make m_Filename protected, so that it is accessible from any derived classes.

**Comment by rsta2** [comment]
Dave, of course you can do, what you want in your code, but the semantics tell me, that `IsAccessAllowed()` only checks for the access permission, while `FileOpen()` opens the file and thus prepares the file name for this. I wouldn't take care too much about some additional code, because the RPi has at least 256 MB.

Rene

**Comment by davefilip** [comment]
Added authorization / default directory / directory access permissions (all part of colorOS) logic to IsAccessAllowed(), and if the filename is modified (by removing the cluster authorization data and adding the default user directory), save the modified file path and name to a new private class variable, and modified FileOpen() and FileCreate() to use that variable, if defined, for the filename instead of the filename parameter.
