### ISSUE TITLE
Raspberry zero - speed settings

### ISSUE THREAD

**Issue by etet100** [rsta2/circle#56]
Hi. As you probably know the default speed settings for raspberry zero are slightly higher than settings for raspberry 1. Since you use fixed values for both raspberry 1 and zero i had to make some modifications in circle core to change speed settings:

1) make CCPUThrottle::SetClockRate public accessible

```
	CCPUThrottle::SetClockRate(CLOCK_ID_CORE, 340 * 1000 * 1000, true);
	CCPUThrottle::SetClockRate(CLOCK_ID_ARM, 1000 * 1000 * 1000, true);

#define CLOCK_ID_SDRAM		8

	CCPUThrottle::SetClockRate(CLOCK_ID_SDRAM, 450 * 1000 * 1000, true);
```
	
2) add voltage related tag to property tags:

```
#define PROPTAG_GET_VOLTAGE	    	0x00030003
#define PROPTAG_SET_VOLTAGE	    	0x00038003

struct TPropertyTagVoltage
{
	TPropertyTag	Tag;
	u32		nVoltageId;
	#define VOLTAGE_ID_CORE		1
	#define VOLTAGE_ID_SDRAM_C	2
	#define VOLTAGE_ID_SDRAM_P	3
	#define VOLTAGE_ID_SDRAM_I	4
	u32		value;
};

struct TPropertyTagSetVoltage
{
	TPropertyTag	Tag;
	u32		nVoltageId;
	u32		value;
};

TagVoltage.nVoltageId = VOLTAGE_ID_CORE;
TagVoltage.value = 1350000; //1,35V
if (Tags.GetTag(PROPTAG_SET_VOLTAGE, &TagVoltage, sizeof TagVoltage, 4))
{
	Message.Format ("CORE Voltage %d %d\r\n", TagVoltage.nVoltageId, TagVoltage.value);
	m_Screen.Write ((const char *) Message, Message.GetLength ());		//return 0;
}
```

Are you planning to implement such routines in nearest future?

**Comment by rsta2** [comment]
These modifications are not really needed to run the RPi Zero at 1 GHz. It's not true, that I use fixed values for the allowed range of the ARM clock rate. *m_nMaxClockRate* is first set to 600 in the constructor of class *CCPUThrottle* but then [overwritten with the actual value requested from the firmware](https://github.com/rsta2/circle/blob/19135be469e2c9a249e73adfab738d36ca6d4b51/lib/cputhrottle.cpp#L61). That is 1000 for the RPi Zero.

You only need to include the *fast=true* option in *cmdline.txt* or include the member initialiser `m_CPUThrottle (CPUSpeedMaximum)` in *CKernel*. Your RPi Zero will run at 1 GHz then. I have tested this again with *sample/26-cpustress*.

I think, the firmware knows best on their own, how to handle turbo mode and voltage settings for different clock rates. I remember, that implementing this CPU clock support was very tricky, so please be careful!

**Comment by etet100** [comment]
Thank you for explanation. I forgot about cmdline setting. 

However, i should mention what i'm trying to achieve. I need to speed up SPI a little bit. Current speed is to low to send 60 frames per second, but next step means twice higher speed, which is way to fast for my LCD. The only solution i found is to speed up core clock or speed up SPI and slow down core clock. This is why i can't use any predefined speed settings.

**Comment by rsta2** [comment]
I have no experiences with overclocking by myself. If you really need this for your application, I would suggest doing it using the settings in [config.txt](https://www.raspberrypi.org/documentation/configuration/config-txt/overclocking.md).

**Comment by rsta2** [comment]
After thinking about this issue again, I decided, that I will not support these overclocking (or underclocking) settings in Circle directly. There are several reasons for this:

* Changing the clock settings in an arbitrary way may be risky.
* Clock settings can be manipulated more safely in config.txt, because it is checked by the firmware. This is the recommended way to do it.
* Your requirements are very special. I don't think, that many people would use such support.
* If you really need these functions, you can implement this by yourself (on your own risk), as you have started it already.

This issue can be closed soon.

**Comment by etet100** [comment]
Hi. You're right. Thanks.
