### ISSUE TITLE
Raspberry Pi 2 support

### ISSUE THREAD

**Issue by meesokim** [rsta2/circle#6]
Is there any plan to support lastest Raspbeery Pi 2? It will be worthy if it is possible.

**Comment by rsta2** [comment]
I'm working on it. It is already running - including MMU and USB - but there are some things left to do. I think I will put it on GitHub in one week or two.

**Comment by meesokim** [comment]
That's good news. Is it possible to use quad-core feature and NEON instruction?

**Comment by kika123** [comment]
@PeterLemon already has a NEON sample

**Comment by rsta2** [comment]
My current focus is to support those features available in Circle on the Raspberry Pi 1 on Pi 2 too. So there won't be a multi-core support at the moment. According to the sample of @PeterLemon a special NEON initialization is not needed. The basic FPU initialization already included in Circle is sufficient. So NEON instructions should be useable.

**Comment by rsta2** [comment]
Raspberry Pi 2 support is commited. In the end it was less work than I thought before.

**Comment by rsta2** [comment]
I think this can be closed. Multi-core support is another issue I will open.
