### ISSUE TITLE
missing timeOut in usbHost->transfer

### ISSUE THREAD

**Issue by noemu** [rsta2/circle#73]
sometimes the Transfer function from CUSBHostController ist getting stuck.

Can you add a timeout, so the code can go on and handle the errors?

**Comment by rsta2** [comment]
The Circle USB HCI driver is not able to recover from errors. Even if there would be a time out parameter, the used USB host channel would be in an unknown state after time out and could not be used any more. Changing this would require lots of work and isn't possible for me at the moment. If *CUSBHostController::Transfer()* gets stuck, this is a serious problem, which must be solved to be able to use this USB device with Circle.
