### ISSUE TITLE
C++ math library

### ISSUE THREAD

**Issue by Siddhartha123** [rsta2/circle#74]
Does circle support the math.h library ? If yes, how to use it ?

**Comment by rsta2** [comment]
Circle does not support math.h by itself. But there is the [circle-stdlib](https://github.com/smuehlst/circle-stdlib) project, which is based on Circle and adds support for the C and C++ standard libraries to Circle. Please have a look on the main README.md and the samples of this project for further information.

**Comment by Siddhartha123** [comment]
Can I get the circle samples built on this project ? Actually I want to use screen class also.

**Comment by Siddhartha123** [comment]
It works ! Thanks.
