### ISSUE TITLE
Updating kernel.img remotely

### ISSUE THREAD

**Issue by GiovanniCmpaner** [rsta2/circle#75]
Hi everyone!

Is there a way right now to update kernel.img remotely, without having to take out the SD Card from the Raspberry?

I tought of handling a socket together with file operations, but I'm asking before to see if it is already available.

Thanks!

**Comment by MaPePeR** [comment]
I think there is a way to do it with serial communication. See https://github.com/rsta2/circle/pull/58

**Comment by rsta2** [comment]
Another possibility is to add a TFTP file server for the SD card root directory to your application as it is described [here](https://github.com/rsta2/circle/blob/master/addon/tftpfileserver/sample/README).

**Comment by GiovanniCmpaner** [comment]
Thanks both, @MaPePeR and @ rsta2, very helpful links!
