### ISSUE TITLE
Build with Cygwin on Windows (arm-none-eabi-g++ 5.4.1)

### ISSUE THREAD

**Issue by xlar54** [rsta2/circle#81]
For others out there, I build with Cygwin on Windows.  Works fine, except that in the current version I have (arm-none-eabi-g++ 5.4.1), there appears to be a compiler bug ("insn does not satisfy its constraints").  The fix is to go into the lib/net directory and open up httpclient.cpp.  Add this pragma before the method name:

#pragma GCC optimize("O0")
THTTPStatus CHTTPClient::Request (THTTPRequestMethod  Method,
				  const char	     *pPath,
				  u8		     *pBuffer,
				  unsigned	     *pLength,
				  const char	     *pFormData)

**Comment by rsta2** [comment]
Thanks for this info. I modified the title, so the entry can be found easier.

**Comment by rsta2** [comment]
I will close this issue, because it's not an open bug in Circle. The issue can be found in the list of closed issues.
