### ISSUE TITLE
NEON/VFP registers are overwritten by interrupt code

### ISSUE THREAD

**Issue by stephanedamo** [rsta2/circle#85]
Hello,

I noticed when I put values in NEON Q registers (Q 0..15 = D 0..31 registers) in the main program loop, if an  interrupt occurs and make use of the same register, its original value isn't restored on interrupt exit.
I "solved" the problem by using the Q15 register which by chance doesn't overlap with the interrupt code (generated by GCC), but it's not a robust solution.
Is that a normal behavior ? Should I do something by hand in my code to handle the context switch properly ?

**Comment by rsta2** [comment]
The interrupt (IRQ) handler saves and restores the general purpose registers only. Floating point registers won't be saved. Theoretical this would be possible, but would radically reduce the system performance. That means that floating point registers (including NEON Q registers) must not be modified in an interrupt service routine. As far I am aware this should be the case for Circle provided interrupt code with the default build options. Or did I missed something?

Furthermore the Circle scheduler only saves and restores the floating point registers D0..15. That means the registers D16..31 (Q8..15) can be used from one task only at a time. Saving more registers would have a negative influence on the task performance. Saving and restoring additional eight Q registers would require to transfer 8*8*2 = 128 bytes on each task switch.

I have to note, that I didn't use NEON features so far, so this is new. Please let me know, if you have special requirements in your application and if I can do something to support them.

**Comment by stephanedamo** [comment]
Maybe i'm missing something too, but with the current -mfpu compilation options in Rules.mk, GCC can generate VFP/NEON instructions from C code. I'm not sure it's the case with the -O2 optimization level, but I have -Ofast for max optimization and there are NEON instructions in the generated assembly. So theorically, not saving/restoring those register could create and infinite number of bugs and strange things when dealing with IRQs/FIQs.

I found an example of IRQ handling that saves/restores VFP registers, it looks like that :

```
IRQHandler:

SUB r14, r14, #4 ; Apply lr correction

STMFD r13!, {r0-r3, r12, r14} ; Save context in IRQ stack

MRS r3, spsr ; Copy spsr

VMRS r1, FPSCR ; Copy fpscr

STMFD r13!, {r1,r3} ; Save fpcr and spsr

VSTMDB [r13]!, {d0-d7} ; Save NEON/VFP scratch registers

LDR r0, ADDR_THRESHOLD ; Get the IRQ Threshold

. (Omit)
.
VLDMIA [r13]!,{d0-d7} ; Restore NEON/VFP scratch registers

LDMFD r13!, {r1, r3} ; get fpscr and spsr from stack

MSR spsr_cxsf, r3 ; Restore spsr

VMSR FPSCR, r1 ; Restore fpscr

LDMFD r13!, {r0-r3, r12, pc}^ ; Restore the context and return
```


An idea could be to add to your current IRQ/FIQ handling code the instructions to handle VFP registers, but only triggered when a #define is set ?

**Comment by stephanedamo** [comment]
Thank you for offering your help, my application is a (maybe professional !) synthesizer, I need to get the highest number of voices to make it up to the current standards. So I looked at optimizing things quite early.
I've got enough performance but now I'm facing those random glitches/crashes. I noticed the lack of context handling for VFP/NEON registers by noticing that my new optimized drawing routings were drawing random things. And I suspect it's also the root cause of the random glitches/crashes I occasionally get.

I can try adding the VSTMDB and VLDMIA instructions to your current IRQ/FIQ handling code (in exceptionstub.S) to see if it fix my problems and get an idea of the performance drawbacks. However I'm quite new to assembly, I don't know if just adding those two instructions is enough.

**Comment by rsta2** [comment]
I will prepare the special interrupt handler until tomorrow. I also want to do some tests on it.

Are you using the FIQ? The FIQ is again more timing sensitive compared to the IRQ and is normally used in Circle only if the application explicitly enables it.

**Comment by stephanedamo** [comment]
I use the FIQ for the serial MIDI input, since I already have an IRQ for the sound generation.
If context switching on FIQ is too problematic I can try polling the serial device directly in the audio callback.

**Comment by rsta2** [comment]
The VFP register saving code has been added. Please checkout the branch *develop* to test it. There are two new system options *SAVE_VFP_REGS_ON_IRQ* and *SAVE_VFP_REGS_ON_FIQ* near to the end of *include/circle/sysconfig.h*, which have to be defined. It's probably better to stay with the FIQ for serial MIDI.

**Comment by stephanedamo** [comment]
Thank you very much. By reading a bit more on the subject I got quite confused, i'm not sure saving the d0-d7 registers like in my example is the right thing to do : 

> Registers v8-v15 must be preserved by a callee across subroutine calls; the remaining registers (v0-v7, v16-v31) do not need to be preserved (or should be preserved by the caller). Additionally, only the bottom 64-bits of each value stored in v8-v15 need to be preserved; it is the responsibility of the caller to preserve larger values.

From : https://stackoverflow.com/questions/261419/what-registers-to-save-in-the-arm-c-calling-convention

Other post : https://stackoverflow.com/questions/5288390/arm-to-c-calling-convention-neon-registers-to-save

And again another source : https://msdn.microsoft.com/en-us/library/dn736986.aspx

Singles | Doubles | Quads | Volatile? | Role
-- | -- | -- | -- | --
s0-s3 | d0-d1 | q0 | Volatile | Parameters, result, scratch register
s4-s7 | d2-d3 | q1 | Volatile | Parameters, scratch register
s8-s11 | d4-d5 | q2 | Volatile | Parameters, scratch register
s12-s15 | d6-d7 | q3 | Volatile | Parameters, scratch register
s16-s19 | d8-d9 | q4 | **Non-volatile** |  
s20-s23 | d10-d11 | q5 | **Non-volatile** |  
s24-s27 | d12-d13 | q6 | **Non-volatile** |  
s28-s31 | d14-d15 | q7 | **Non-volatile** |  
  | d16-d31 | q8-q15 | Volatile

I'll do some tests and let you know

**Comment by rsta2** [comment]
As I understand this, d16-d31 have to be additionally saved and restored. At the moment only d0-d7 are saved/restored. If you want to test this, you have to replace `{d0-d7}` with `{d0-d7, d16-d31}` everywhere in *lib/exceptionstub.S*.

**Comment by stephanedamo** [comment]
I've saved/restored the whole d0-d31 registers as GCC used most of them in the generated assembly. The load/store instruction can take up to 16x64bits so it needs to be done in two steps. Everything is running rock solid now, no more random behaviors/crashes.

Performance-wise, my app was already quite close to the cpu limits but I haven't found a noticeable difference with or without those additional register handling. Serial (FIQ) speed is 31250, and the audio IRQ happens 375 times/sec.

**Comment by rsta2** [comment]
This is good news! I will modify *lib/exceptionstub.S* so that D0-31 is saved. Please note that in the given link the VFP registers will only be saved in *osRtxContextSwitch* not in *IRQ_Handler*. A context switch is normally only caused by a scheduler, not by an interrupt handler.

**Comment by rsta2** [comment]
The modification is on the *develop* branch now. Please note that `__FAST_MATH__` will be defined automatically by GCC, if `-Ofast` is specified. *Rules.mk* has been updated too to make this work on assembler source files.

**Comment by stephanedamo** [comment]
Great work thank you !

**Comment by rsta2** [comment]
Thank you also for your help while figuring this out!

**Comment by rsta2** [comment]
The modification is on *master* branch now.
